### ISSUE TITLE
The function for pcharlist seems to be missing

### ISSUE THREAD

**Issue by raphaelcohn** [luapower/libcurl#2]
* When I try and require this code, it fails to compile because `pcharlist` isn't defined anywhere

**Comment by capr** [comment]
How are you compiling it? Are you using the prescribed toolchain? Which platform are you on?

**Comment by raphaelcohn** [comment]
I'm in Mac OS X.
Using luajit 2.0.4.
Not compiling but using as is against system libcurl.

On 11 Jan 2017 2:29 p.m., "Cosmin Apreutesei" <notifications@github.com>
wrote:

How are you compiling it? Are you using the prescribed toolchain? Which
platform are you on?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/luapower/libcurl/issues/2#issuecomment-271882241>, or mute
the thread

**Comment by capr** [comment]
Fixed. Please pull master and try again.
